{   'assets': {   'web.assets_backend': [   'report_xlsx/static/src/js/report/action_manager_report.esm.js']},
    'author': 'Joel S. Martinez espinal',
    'category': 'Reporting',
    'demo': ['demo/report.xml'],
    'depends': ['base', 'web'],
    'development_status': 'Mature',
    'external_dependencies': {'python': ['xlsxwriter', 'xlrd']},
    'installable': True,
    'license': 'AGPL-3',
    'maintainers': ['Joel S. Martinez espinal'],
    'name': 'Base report xlsx',
    'summary': 'Base module to create xlsx report',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/reporting-engine'}