

services:
  odoo18:
    image: odoo:18.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - odoo18-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
      - ./config:/etc/odoo
    environment:
      - DB_HOST=postgres
      - DB_NAME=odoo_db
      - DB_USER=odoo
      - DB_PASSWORD=odoo_pass
    command: odoo -d odoo_db --init=base  --logfile /var/log/odoo/odoo.log --stop-after-init
    restart: always


  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_pass
      - POSTGRES_DB=odoo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always


volumes:
  odoo18-data:
  postgres-data:
